
import { Tables } from "@/integrations/supabase/types";

export const createVehicleHomeownersData = (): Partial<Tables<"clients">> => ({
  // Vehicle coverage fields
  vehicle_carrier: null,
  vehicle_6_month_premium: 0,
  vehicle_expiration_date: null,
  vehicle_annual_premium: 0,
  vehicle_6_month_premium_proposed: 0,
  vehicle_savings: 0,
  vehicle_app_date: null,
  vehicle_status: null,
  vehicle_status_date: null,
  vehicle_issue_date: null,
  vehicle_disburse_date: null,
  vehicle_dft: null,
  vehicle_dft_number: null,
  vehicle_units: false,
  
  // Homeowners fields
  homeowners_current_premium: 0,
  homeowners_proposed_premium: 0,
  homeowners_savings: 0,
  homeowners_app_date: null,
  homeowners_issue_date: null,
  homeowners_status_date: null,
  homeowners_disclosure_date: null,
  homeowners_units: false,
  homeowners_year_built: null,
  homeowners_purchase_date: null,
  homeowners_mortgage_balance: 0,
  homeowners_payment: 0,
  homeowners_mo_rental_income: 0,
  homeowners_square_footage: null,
  homeowners_foundation_percent: 0,
  homeowners_sq_ft_general_features: 0,
  homeowners_fireplace_count: 0,
  homeowners_deck_sq_footage: 0,
  homeowners_open_porch_sq_ft: 0,
  homeowners_enclosed_porch_sq_ft: 0,
  homeowners_pets_count: 0,
  homeowners_car_garage_count: 0,
  homeowners_full_bath_count: 0,
  homeowners_half_bath_count: 0,
  homeowners_claims_past_5_years: 0,
  homeowners_claims_amount: 0,
  homeowners_medical_payments_current: 0,
  homeowners_medical_payments_proposed: 0,
  homeowners_property_value: 0,
  homeowners_hm_assoc_fee: 0,
  homeowners_account_credit: 0,
  homeowners_fire_extinguisher: null,
  homeowners_self_loading_gate: null,
  homeowners_flood_policy: null,
  homeowners_monitored_burglar_alarm: null,
  homeowners_smoke_detector: null,
  homeowners_housing_type: null,
  homeowners_style: null,
  homeowners_owner_occupied: null,
  homeowners_tenant_occupied: null,
  homeowners_monitored_fire_alarm: null,
  homeowners_current_deductible: null,
  homeowners_foundation: null,
  homeowners_proposed_deductible: null,
  homeowners_construction: null,
  homeowners_roof: null,
  homeowners_offered_for_sale: null,
  homeowners_refinanced: null,
  homeowners_business_operated: null,
  homeowners_non_smoking_household: null,
  homeowners_24_hour_security_guard: null,
  homeowners_address: null,
  homeowners_city: null,
  homeowners_state: null,
  homeowners_current_provider: null,
  homeowners_liability_current: null,
  homeowners_pool: null,
  homeowners_liability_proposed: null,
  homeowners_trampoline: null,
  homeowners_status: null,
  homeowners_property_description: null,
  homeowners_deadbolt_locks: null,
  homeowners_policy_number: null,
  homeowners_garage: null,
  homeowners_dft: null,
  homeowners_dft_number: null,
});
