
-- Add missing fields to the clients table to support the comprehensive form
ALTER TABLE public.clients 
ADD COLUMN IF NOT EXISTS coapplicant_title TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_first_name TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_mi TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_last_name TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_suffix TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_maiden_name TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_is_consultant BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS coapplicant_address TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_city TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_county TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_state TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_zip_code TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_time_at_address TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_previous_address TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_previous_address_time TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_home_phone TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_other_phone TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_fax TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_employment_status TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_business_owner TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_employer_name TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_employer_address TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_employer_city TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_employer_state TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_employer_zip TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_occupation TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_monthly_salary NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS coapplicant_employer_phone TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_start_date DATE,
ADD COLUMN IF NOT EXISTS coapplicant_end_date DATE,
ADD COLUMN IF NOT EXISTS coapplicant_additional_income NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS coapplicant_additional_income_source TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_previous_employer TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_previous_employer_address TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_previous_occupation TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_previous_employment_from DATE,
ADD COLUMN IF NOT EXISTS coapplicant_previous_employment_to DATE,
ADD COLUMN IF NOT EXISTS coapplicant_dob DATE,
ADD COLUMN IF NOT EXISTS coapplicant_ssn TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_birth_place TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_race TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_marital_status TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_anniversary DATE,
ADD COLUMN IF NOT EXISTS coapplicant_spouse_name TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_spouse_occupation TEXT,
ADD COLUMN IF NOT EXISTS coapplicant_dependents_count INTEGER DEFAULT 0;
