
-- Add fields for Loan Status tab
ALTER TABLE public.mortgages 
ADD COLUMN IF NOT EXISTS lender_id_field text,
ADD COLUMN IF NOT EXISTS loan_status text,
ADD COLUMN IF NOT EXISTS status_date date,
ADD COLUMN IF NOT EXISTS appraisal_ordered date,
ADD COLUMN IF NOT EXISTS appraisal_received date,
ADD COLUMN IF NOT EXISTS appraisal_company text,
ADD COLUMN IF NOT EXISTS appraisal_invoice text,
ADD COLUMN IF NOT EXISTS app_amt numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS appraisal_paid numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS courier_fee numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS admin_fee numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS modified_by text,
ADD COLUMN IF NOT EXISTS modified_date date,
ADD COLUMN IF NOT EXISTS date_in date,
ADD COLUMN IF NOT EXISTS time_in time,
ADD COLUMN IF NOT EXISTS clw_sent date,
ADD COLUMN IF NOT EXISTS clw_rec date,
ADD COLUMN IF NOT EXISTS pa_sent date,
ADD COLUMN IF NOT EXISTS pa_rec_d date,
ADD COLUMN IF NOT EXISTS vom_contact text,
ADD COLUMN IF NOT EXISTS vom_phone text,
ADD COLUMN IF NOT EXISTS title_ordered date,
ADD COLUMN IF NOT EXISTS title_rec_d date,
ADD COLUMN IF NOT EXISTS title_co_name text,
ADD COLUMN IF NOT EXISTS title_binder text,
ADD COLUMN IF NOT EXISTS title_pld text,
ADD COLUMN IF NOT EXISTS sales_support text,
ADD COLUMN IF NOT EXISTS ss_auditor text,
ADD COLUMN IF NOT EXISTS contract_pf text,
ADD COLUMN IF NOT EXISTS contract_cc text,
ADD COLUMN IF NOT EXISTS field_trainer text,
ADD COLUMN IF NOT EXISTS voe_sent date,
ADD COLUMN IF NOT EXISTS voe_rec date,
ADD COLUMN IF NOT EXISTS voe_contact text,
ADD COLUMN IF NOT EXISTS voe_phone text,
ADD COLUMN IF NOT EXISTS vom_sent date,
ADD COLUMN IF NOT EXISTS vom_rec date,
ADD COLUMN IF NOT EXISTS final_sent date,
ADD COLUMN IF NOT EXISTS final_rec_d date,
ADD COLUMN IF NOT EXISTS cleared_date date,
ADD COLUMN IF NOT EXISTS closed_date date,
ADD COLUMN IF NOT EXISTS funded_date date,
ADD COLUMN IF NOT EXISTS funded_amt numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS disburse_date date;

-- Add fields for Vehicle Coverage tab
ALTER TABLE public.clients 
ADD COLUMN IF NOT EXISTS vehicle_carrier text,
ADD COLUMN IF NOT EXISTS vehicle_6_month_premium numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS vehicle_expiration_date date,
ADD COLUMN IF NOT EXISTS vehicle_annual_premium numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS vehicle_6_month_premium_proposed numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS vehicle_savings numeric DEFAULT 0,
ADD COLUMN IF NOT EXISTS vehicle_app_date date,
ADD COLUMN IF NOT EXISTS vehicle_status text,
ADD COLUMN IF NOT EXISTS vehicle_status_date date,
ADD COLUMN IF NOT EXISTS vehicle_issue_date date,
ADD COLUMN IF NOT EXISTS vehicle_disburse_date date,
ADD COLUMN IF NOT EXISTS vehicle_dft text,
ADD COLUMN IF NOT EXISTS vehicle_dft_number text,
ADD COLUMN IF NOT EXISTS vehicle_units boolean DEFAULT false;
